#!/usr/bin/env sh

# Help script

printf "Audio: pavucontrol\n"

printf "Conf i3: xprop"
printf "Screen: xrandr --output <name> --auto\n"
printf "Screen: xrandr --output <name> --left/right-of <name>\n"
printf "Screen: xrandr --output <name> --same-as <name>\n"

printf "User: useradd <name> --create-home -p <pass>\n"
printf "User: userdel -r <name>\n"

printf "Security: sudo rkhunter --checkall"
