#!/usr/bin/env bash

# +---------------+
# |  Lock script  |
# +---------------+

#------ VAR -------#
IMG=/tmp/screenshot.png
ICON=$HOME/.dotfiles/res/lock.png

#------ TRANSFORMATIONS ------
import -window root $IMG
convert  $IMG  -blur 0x4  $IMG
convert $IMG -colorspace LinearGray $IMG
convert $IMG $ICON -gravity center -composite $IMG

#-------- LOCK -------
i3lock -u -i $IMG
