###########################
# Étienne "maiste" Marais #
#    Starship Config      #
#    Version 20210125     #
###########################


##---------- STYLE --------------##
format = """
$hostname\
$directory\
$git_branch\
$git_status\
$git_state\
$dart\
$golang\
$java\
$nodejs\
$ocaml\
$python\
$rust
$nix_shell\
$character"""

[character]
format = "$symbol "
success_symbol = "[λ](bold yellow)"
error_symbol   = "[λ](bold red)"


##------ LOCAL MODULES ----------##
[username]
format = "[$user]($style)"
style_root = "bold red"
style_user = "bold blue"
show_always = true

[hostname]
format = "[$hostname]($style)"
style = "bold blue"
ssh_only = false

[directory]
format = " >>= [$path]($style)[$read_only]($read_only_style)"
style = "bold cyan"
truncation_length = 2


##--------- GIT MODULES --------##
[git_branch]
format = "::[$branch]($style)"
style = "bold purple"

[git_state]
format = "[$state: $progress_current/$progress_total]($style)"
style = "bold purple"
rebase = "R"
merge = "M"
revert = "Rev"
cherry-pick = "CP"
bisect = "B"
am = "AM"
am_or_rebase = "AMR"

[git_status]
untracked = "?"
stashed = ""
modified = "~"
staged = "+"
renamed = "r"
deleted = "-"
style = "bold purple"


##-------- LANG MODULES -------##
[dart]
format= " >>= [da:$version]($style)"
style = "bold green"

[golang]
format = " >>= [go:$version]($style)"
style = "bold green"

[java]
format = " >>= [jv:$version]($style)"
style = "bold green"

[nodejs]
format = " >>= [nd:$version]($style)"
style = "bold green"

[ocaml]
format = " >>= [ml:$version]($style)"
style = "bold green"

[python]
format = " >>= [py:${pyenv_prefix}(${virtualenv}->)${version}]($style)"
style = "bold green"

[rust]
format = " >>= [ru:$version]($style)"
style = "bold red"

[nix_shell]
format  = "[$name->$state]($style)"
stule = "bold blue"
