#!/usr/bin/env bash

###########################
# Maiste <dev@maiste.fr>  #
#      Linking script     #
#    Version 20210325     #
###########################

cd "$(dirname $0)/.."

printf "\n\n"
printf "+-------------------------+\n"
printf "|  Linking configuration  |\n"
printf "+-------------------------+\n\n"

printf "ROOT DIRECTORY: %s\n" $PWD



#-------------- Remove ------------#

printf "\n#----- Remove links -----#\n"

remove_link () {
  printf " - Remove %s\n" $1
  rm -rf $1
}

remove_link "$HOME/.zshrc"
remove_link "$HOME/.gitconfig"
remove_link "$HOME/.Xresources"
remove_link "$HOME/.config/alacritty"
remove_link "$HOME/.config/starship"
remove_link "$HOME/.config/zsh"
remove_link "$HOME/.config/i3"
remove_link "$HOME/.config/rofi"
remove_link "$HOME/.config/dunst"
remove_link "$HOME/.berkelium"
remove_link "$HOME/.config/nvim"
remove_link "$HOME/.config/.emacs.d"
remove_link "$HOME/.config/asset"
remove_link "$HOME/.config/sway"
remove_link "$HOME/.config/kanshi"



#-------------- Install ------------#

printf "\n#----- Install links -----#\n"

install_link () {
  printf " - Link bundle %s\n" $1
  stow -v $1
}

install_link "terminal"
install_link "desktop"
install_link "editor"
install_link "asset"
